build:
  maxIssues: 0

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 150

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]

complexity:
  LongMethod:
    active: true
    threshold: 60
  TooManyFunctions:
    active: false

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
